title = "Media Tracker"
baseURL = 'https://christt105.github.io/MediaTracker'
languageCode = 'es-es'
defaultContentLanguage = "es"
enableEmoji = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

# --- MENÚ DE NAVEGACIÓN ---
[menu]
  [[menu.main]]
    pageRef="/"
    name = 'Inicio'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="movies" # Apunta a tus carpetas nuevas
    name = 'Películas'
    url = '/movies/'
    weight = 20
  [[menu.main]]
    pageRef="tv"
    name = 'Series'
    url = '/tv/'
    weight = 40
  [[menu.main]]
    pageRef="games"
    name = 'Juegos'
    url = '/games/'
    weight = 30

# --- CONFIGURACIÓN DEL SITIO ---
[params]
  sitename = "Media Tracker"
  defaultColor = "dark" # dark, light, o auto
  description = "Mi colección personal de películas y videojuegos."
  mainSections = ['movies', 'games', 'tv'] # Importante para que Hugo sepa qué listar
  
  # Opciones visuales
  toc = true 
  goToTop = true
  dateFormat = "2 Jan 2006"

# --- TU PERFIL (BIO) ---
[params.author]
  avatar = "avatar.webp"
  intro = "Media Tracker"
  name = "christt105"
  description = "Este es mi rincón personal donde guardo un registro de todo lo que consumo. Automatizado con Obsidian y Hugo."

# --- REDES SOCIALES (Opcional) ---
[[params.socialIcons]]
name = "github"
url = "https://github.com/christt105"

[[params.socialIcons]]
name = "rss"
url = "/MediaTracker/index.xml"