title = "Media Tracker"
baseURL = 'https://christt105.github.io/MediaTracker/'
languageCode = 'es-es'
defaultContentLanguage = "es"
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[menu]
  [[menu.main]]
    pageRef="movies"
    name = 'Películas'
    url = '/movies/'
    weight = 20
  [[menu.main]]
    pageRef="tv"
    name = 'Series'
    url = '/tv/'
    weight = 40
  [[menu.main]]
    pageRef="games"
    name = 'Juegos'
    url = '/games/'
    weight = 30
  [[menu.main]]
    pageRef="collage"
    name = 'Collage'
    url = '/collage/'
    weight = 50
  [[menu.main]]
    pageRef="about"
    name = 'Acerca de'
    url = '/about/'
    weight = 60

[params]
  sitename = "Media Tracker"
  defaultColor = "dark"
  description = "Mi colección personal de películas, series y videojuegos."
  mainSections = ['movies', 'games', 'tv'] 

  toc = false 
  goToTop = true
  dateFormat = "2 Jan 2006"

[params.author]
  avatar = "avatar.webp"
  intro = "Media Tracker"
  name = "christt105"
  description = "Este es mi rincón personal donde guardo un registro de todas las películas, series y videojuegos que consumo. Generado con Obsidian y Hugo."

[[params.socialIcons]]
name = "github"
url = "https://github.com/christt105"

[[params.socialIcons]]
name = "rss"
url = "/MediaTracker/index.xml"